### ISSUE TITLE
Phylogenetic tree data

### ISSUE THREAD

**Issue by BioinformaticEmilio** [chasemc/IDBac_App#12]
Hi, 

Would it be possible to export the phylogenetic tree data to view/modify it with other software?

**Comment by chasemc** [comment]
Yeah, absolutely! But not yet, it's on my list for the next update.  I'll offer nexus, any other file format preferences?

**Comment by BioinformaticEmilio** [comment]
Cool thanks! Nexus is good, but I know people in my lab would appreciate also MEGA.

**Comment by chasemc** [comment]
Temp fix: Copy this as the server.r : 

https://gist.github.com/chasemc/57a880cc7f9b3ab6c4040e31275376e1

**Comment by BioinformaticEmilio** [comment]
Nice thanks!
