### ISSUE TITLE
Error - Hierarchical clustering

### ISSUE THREAD

**Issue by marysofia** [chasemc/IDBac_App#13]
Step - Hierarchical clustering:
When I uploaded the excel file with the information about my samples (media, location, etc) to color samples according the groups, I have some problems. When I upload nothing change, but then if I change the variables (Select a goup mapping), other error appear (subscript out of bonds). I am afraid it is the excel file. Do you have the same result?

**Comment by chasemc** [comment]
It looks like it is mostly the excel file (missing values) maybe special characters. I'll work on the excel file today, and work on the software to try and account for things like this when possible.
