### ISSUE TITLE
Creating IDBac folder

### ISSUE THREAD

**Issue by marysofia** [chasemc/IDBac_App#7]
The IDBac folder can not be created in the same directory that you have your data.

**Comment by chasemc** [comment]
You'll have to be more specific about the process you followed that didn't work. It is possible to choose the same directory. Issues might arise if you try to convert the raw data a second time. But you should notice the folder "IDBac" being listed as a raw data folder and that should warn you to reevaluate how your directories are arranged.
I'm a little hesitant to make it ignore folders named IDBac. I'll have to think about it
