### ISSUE TITLE
MAN'S

### ISSUE THREAD

**Issue by marysofia** [chasemc/IDBac_App#9]
I generated all the spectra, I have the hierarchical clustering and PCA but, When I go to the MAN, I can not see the network. I have the HC below but not the MAN above. The message that appear is "mergeMassPeaks(combinedSmallMolPeaksm) : 'l' is no list of MALDIquant::MassPeaks objects!"".

Maybe this isn't a bug, it is my data.. but... I can not find why appeared.

**Comment by chasemc** [comment]
This will be fixed in the next version. But it's most likely you don't have a matrix blank
